import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://anbkhizdpgtyjpjbokeu.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuYmtoaXpkcGd0eWpwamJva2V1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzM3MTIyMiwiZXhwIjoyMDkyOTQ3MjIyfQ.nMMrcUpyWEPghIfwyyrZSRRrxbdBngOTaYQHPOF96qE',
  { auth: { autoRefreshToken: false, persistSession: false } }
)

const events = [
  {
    title: 'NUS Hack & Roll 2026',
    description: 'Singapore\'s largest student-run hackathon, hosted by NUS Hackers. Build something cool in 24 hours and compete for prizes across categories including AI, sustainability, and open-source tooling.',
    start_at: '2026-05-03T09:00:00+08:00',
    end_at: '2026-05-04T12:00:00+08:00',
    location_name: 'NUS School of Computing, COM1',
    location_address: '13 Computing Drive, Singapore 117417',
    coordinates: { lat: 1.2951, lng: 103.7743 },
    image_url: null,
    external_url: 'https://hacknroll.nushackers.org',
    source: 'submitted',
    source_id: null,
    tags: ['hackathon', '24-hours', 'prizes', 'AI', 'open-source'],
    category: 'hackathon',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'NUS Hackers',
    organiser_id: null,
  },
  {
    title: 'NTU Career Fair Spring 2026',
    description: 'Connect with 80+ top employers across engineering, finance, tech, and consulting. Bring printed resumes and dress professionally. Open to all NTU students and alumni within 5 years of graduation.',
    start_at: '2026-05-07T10:00:00+08:00',
    end_at: '2026-05-07T17:00:00+08:00',
    location_name: 'NTU The Hive (Learning Hub)',
    location_address: '50 Nanyang Ave, Singapore 639798',
    coordinates: { lat: 1.3484, lng: 103.6831 },
    image_url: null,
    external_url: null,
    source: 'submitted',
    source_id: null,
    tags: ['career', 'networking', 'recruitment', 'internship', 'full-time'],
    category: 'career',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'NTU Career & Attachment Office',
    organiser_id: null,
  },
  {
    title: 'SP Open House 2026',
    description: 'Explore Singapore Polytechnic\'s 30+ diploma courses, tour state-of-the-art labs and facilities, and chat with current students and lecturers. Perfect for O-Level and N-Level students deciding their next step.',
    start_at: '2026-05-10T09:00:00+08:00',
    end_at: '2026-05-10T17:00:00+08:00',
    location_name: 'Singapore Polytechnic Main Campus',
    location_address: '500 Dover Rd, Singapore 139651',
    coordinates: { lat: 1.3109, lng: 103.7787 },
    image_url: null,
    external_url: 'https://www.sp.edu.sg/sp/about-sp/open-house',
    source: 'submitted',
    source_id: null,
    tags: ['open house', 'polytechnic', 'courses', 'diploma', 'admissions'],
    category: 'open_house',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'Singapore Polytechnic',
    organiser_id: null,
  },
  {
    title: 'SMU Fintech Innovation Workshop',
    description: 'A hands-on workshop covering blockchain fundamentals, DeFi protocols, and building simple smart contracts on Ethereum. Facilitated by SMU Blockchain Club with guest speakers from local fintech startups.',
    start_at: '2026-05-13T14:00:00+08:00',
    end_at: '2026-05-13T18:00:00+08:00',
    location_name: 'SMU School of Information Systems, SIS Seminar Room 2.1',
    location_address: '80 Stamford Rd, Singapore 178902',
    coordinates: { lat: 1.2966, lng: 103.8502 },
    image_url: null,
    external_url: null,
    source: 'submitted',
    source_id: null,
    tags: ['fintech', 'blockchain', 'workshop', 'smart contracts', 'ethereum'],
    category: 'workshop',
    status: 'published',
    is_free: false,
    price_min: 10,
    price_max: 10,
    organiser_name: 'SMU Blockchain Club',
    organiser_id: null,
  },
  {
    title: 'NUS Inter-Faculty Futsal Tournament',
    description: 'Annual inter-faculty futsal competition open to all NUS undergraduates. Register a 5-a-side team representing your faculty. Round-robin group stage followed by knockout rounds. Trophies and prizes for top 3 teams.',
    start_at: '2026-05-17T08:00:00+08:00',
    end_at: '2026-05-17T18:00:00+08:00',
    location_name: 'NUS University Sports Centre, Futsal Courts',
    location_address: '119 AYE, Singapore 117571',
    coordinates: { lat: 1.3002, lng: 103.7743 },
    image_url: null,
    external_url: null,
    source: 'submitted',
    source_id: null,
    tags: ['futsal', 'sports', 'inter-faculty', 'tournament', 'undergraduate'],
    category: 'sports',
    status: 'published',
    is_free: false,
    price_min: 30,
    price_max: 30,
    organiser_name: 'NUS Sports Club',
    organiser_id: null,
  },
  {
    title: 'SUTD AI & Robotics Demo Day',
    description: 'Showcase event where SUTD student teams present their semester-long AI and robotics projects. Open to the public. Includes live robot demonstrations, Q&A with student engineers, and networking with industry mentors.',
    start_at: '2026-05-19T13:00:00+08:00',
    end_at: '2026-05-19T17:30:00+08:00',
    location_name: 'SUTD Campus Centre',
    location_address: '8 Somapah Rd, Singapore 487372',
    coordinates: { lat: 1.3413, lng: 103.9638 },
    image_url: null,
    external_url: 'https://www.sutd.edu.sg',
    source: 'submitted',
    source_id: null,
    tags: ['AI', 'robotics', 'demo day', 'engineering', 'student projects'],
    category: 'workshop',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'SUTD Student Government',
    organiser_id: null,
  },
  {
    title: 'NYP Open House 2026',
    description: 'Discover Nanyang Polytechnic\'s engineering, design, business, and health science courses. Get hands-on with lab equipment, attend mini-lectures, and find out about scholarships and bursaries available to new students.',
    start_at: '2026-05-22T09:30:00+08:00',
    end_at: '2026-05-22T16:30:00+08:00',
    location_name: 'Nanyang Polytechnic Main Campus',
    location_address: '180 Ang Mo Kio Ave 8, Singapore 569830',
    coordinates: { lat: 1.3801, lng: 103.8490 },
    image_url: null,
    external_url: 'https://www.nyp.edu.sg/openhouse',
    source: 'submitted',
    source_id: null,
    tags: ['open house', 'polytechnic', 'admissions', 'diploma', 'scholarship'],
    category: 'open_house',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'Nanyang Polytechnic',
    organiser_id: null,
  },
  {
    title: 'SIT UX Design Bootcamp',
    description: 'A two-day intensive bootcamp covering user research, wireframing with Figma, and usability testing. Participants will redesign a real app chosen by vote. Breakfast and lunch provided on both days. Certificate issued on completion.',
    start_at: '2026-05-24T09:00:00+08:00',
    end_at: '2026-05-25T17:00:00+08:00',
    location_name: 'SIT@Dover, Design Studio 3',
    location_address: '10 Dover Drive, Singapore 138683',
    coordinates: { lat: 1.3122, lng: 103.7785 },
    image_url: null,
    external_url: null,
    source: 'submitted',
    source_id: null,
    tags: ['UX', 'design', 'Figma', 'bootcamp', 'certificate'],
    category: 'workshop',
    status: 'published',
    is_free: false,
    price_min: 25,
    price_max: 25,
    organiser_name: 'SIT Design & Innovation Club',
    organiser_id: null,
  },
  {
    title: 'NTU x NUS Inter-University Swimming Gala',
    description: 'Biannual competitive swimming meet between NTU and NUS student-athletes. Events include freestyle, backstroke, breaststroke, butterfly, and relays across multiple distance categories. Spectators welcome free of charge.',
    start_at: '2026-05-26T08:00:00+08:00',
    end_at: '2026-05-26T14:00:00+08:00',
    location_name: 'NTU Aquatic Centre',
    location_address: '60 Nanyang Ave, Singapore 639798',
    coordinates: { lat: 1.3497, lng: 103.6821 },
    image_url: null,
    external_url: null,
    source: 'submitted',
    source_id: null,
    tags: ['swimming', 'inter-university', 'gala', 'competitive', 'sports'],
    category: 'sports',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'NTU Sports & Recreation Centre',
    organiser_id: null,
  },
  {
    title: 'TP Startup Pitch Night',
    description: 'Temasek Polytechnic students pitch their startup ideas to a panel of VCs and startup founders. 8 finalists compete for S$5,000 in seed funding. Audience vote determines the People\'s Choice award. Networking session after.',
    start_at: '2026-05-28T18:30:00+08:00',
    end_at: '2026-05-28T21:30:00+08:00',
    location_name: 'Temasek Polytechnic, Enterprise & Innovation Hub',
    location_address: '21 Tampines Ave 1, Singapore 529757',
    coordinates: { lat: 1.3453, lng: 103.9320 },
    image_url: null,
    external_url: null,
    source: 'submitted',
    source_id: null,
    tags: ['startup', 'pitch', 'entrepreneurship', 'funding', 'networking'],
    category: 'career',
    status: 'published',
    is_free: true,
    price_min: null,
    price_max: null,
    organiser_name: 'TP Entrepreneurship Club',
    organiser_id: null,
  },
]

const { data, error } = await supabase.from('events').insert(events).select('id, title')

if (error) {
  console.error('Insert failed:', error.message)
  console.error(error.details ?? '')
  process.exit(1)
}

console.log(`Inserted ${data.length} events:`)
data.forEach(e => console.log(` ✓ ${e.title} (${e.id})`))
